import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/appcomponents/Navbar";

import Providers from "./providers";
const inter = Inter({ subsets: ["latin"] });
import "@rainbow-me/rainbowkit/styles.css";
import ContractContextProvider from "@/Context/contractContect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <ContractContextProvider>
        <body className={inter.className}>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </ContractContextProvider>
    </html>
  );
}
